apiVersion: v1
kind: Service
metadata:
  name: my-tomcat-service
  labels:
    name: my-tomcat-service
    app: demo-user-app
spec:
  type: LoadBalancer
  ports:
    - port: 8443
      targetPort: 8443
  selector:
    name: my-tomcat
    app: demo-user-app
