apiVersion: v1
kind: Service
metadata:
  name: my-mysql
  labels:
    name: my-mysql
    app: demo-user-app
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: my-mysql
    app: demo-user-app
