apiVersion: v1
kind: Service
metadata:
  name: my-openldap
  labels:
    name: my-openldap-service
    app: demo-user-app
spec:
  ports:
    - port: 389
      targetPort: 389
  selector:
    name: my-openldap
    app: demo-user-app
